version: "3.4"

x-common-environment: &common-environment
   DEADEYE_DOCKER: 1
   DEADEYE_NT_SERVER: 192.168.1.11

volumes:
  upload_data:

services:
  daemon:
    image: deadeye-daemon
    build: ./daemon
    ports:
      - "5805:5805"
    volumes:
      - upload_data:/upload
    environment: *common-environment
  admin:
    image: deadeye-admin
    build: ./admin
    ports:
      - "5000:5000"
    volumes:
      - upload_data:/upload
    environment:
      <<: *common-environment
      PYTHONPATH: /app
      FLASK_ENV: production
      DEADEYE_ADMIN_PORT: 5000
      DEADEYE_NT_WAIT_MS: 500
      DEADEYE_UPLOAD_DIR: /upload
  web:
    image: deadeye-web
    build: ./web
    ports:
      - "8080:80"
