version: "3.4"

x-common-environment: &common-environment
  DEADEYE_DOCKER: 1
  DEADEYE_NT_SERVER: 192.168.1.11

x-common-restart: &common-restart
  restart: on-failure

volumes:
  upload_data:

services:
  daemon:
    image: j3ff/deadeye-daemon
    privileged: true
    ports:
      - 5805:5805
      - 5806:5806
      - 5807:5807
      - 5808:5808
      - 5809:5809
    volumes:
      - upload_data:/upload
      - /tmp/argus_socket:/tmp/argus_socket
    devices:
      - /dev/gpiochip0
    environment: *common-environment
    <<: *common-restart
  admin:
    image: j3ff/deadeye-admin
    ports:
      - 5000:5000
    volumes:
      - upload_data:/upload
    environment:
      <<: *common-environment
      PYTHONPATH: /app
      FLASK_ENV: production
      DEADEYE_ADMIN_PORT: 5000
      DEADEYE_NT_WAIT_MS: 500
      DEADEYE_UPLOAD_DIR: /upload
    stop_grace_period: 1s
    stop_signal: SIGINT
    <<: *common-restart
  web:
    image: j3ff/deadeye-web
    ports:
      - "0.0.0.0:80:80"
    <<: *common-restart
