---
- name: Unarchive sources
  ansible.builtin.unarchive:
    src: https://github.com/gabime/spdlog/archive/v{{ spdlog_version }}.tar.gz
    dest: /usr/local/src
    remote_src: true
  tags:
    - spdlog

- name: Create build directory
  ansible.builtin.file:
    path: /usr/local/src/spdlog-{{ spdlog_version }}/build
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - spdlog

- name: Run cmake
  ansible.builtin.command:
    chdir: /usr/local/src/spdlog-{{ spdlog_version }}/build
    argv:
      - /usr/bin/cmake
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr/local
      - -DSPDLOG_FMT_EXTERNAL=ON
      - -GNinja
      - ..
  tags:
    - spdlog
    - build
    - cmake

- name: Build and install
  ansible.builtin.command:
    chdir: /usr/local/src/spdlog-{{ spdlog_version }}/build
    argv:
      - /usr/bin/ninja
      - install
  tags:
    - spdlog
    - build
