---
- name: Install OpenCV prereqs
  ansible.builtin.apt:
    update_cache: true
    name:
      - build-essential
      - cmake
      - ninja-build
      - pkg-config
      - libjpeg-dev
      - libtiff5-dev
      - libpng-dev
      - libavcodec-dev
      - libavformat-dev
      - libswscale-dev
      - libv4l-dev
      - libxvidcore-dev
      - libx264-dev
      - libgtk-3-dev
      - libatlas-base-dev
      - gfortran
      - libcairo2-dev
      - libfontconfig1-dev
      - libgdk-pixbuf2.0-dev
      - libpango1.0-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer1.0-0
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
  tags:
    - opencv

- name: Unarchive sources
  ansible.builtin.unarchive:
    src: https://github.com/opencv/opencv/archive/{{ opencv_version }}.tar.gz
    dest: /usr/local/src
    remote_src: true
  tags:
    - opencv

- name: Create build directory
  ansible.builtin.file:
    path: /usr/local/src/opencv-{{ opencv_version }}/build
    state: directory
    mode: 0755
    owner: root
    group: root
  tags:
    - opencv

- name: Run cmake
  ansible.builtin.command:
    chdir: /usr/local/src/opencv-{{ opencv_version }}/build
    argv:
      - /usr/bin/cmake
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr/local
      - -DENABLE_NEON={{ "ON" if ansible_architecture == "aarch64" else "OFF" }}
      - -DENABLE_VFPV3={{ "ON" if ansible_architecture == "aarch64" else "OFF" }}
      - -DBUILD_TESTS=OFF
      - -DWITH_GSTREAMER=ON
      - -DWITH_GSTREAMER_0_10=OFF
      - -DINSTALL_PYTHON_EXAMPLES=OFF
      - -DBUILD_EXAMPLES=OFF
      - -GNinja
      - ..
  tags:
    - opencv
    - build
    - cmake

- name: Build and install
  ansible.builtin.command:
    chdir: /usr/local/src/opencv-{{ opencv_version }}/build
    argv:
      - /usr/bin/ninja
      - install
  tags:
    - opencv
    - build
