---
- name: "Install aptitude, required by ansible"
  command: apt-get install -y aptitude
  args:
    creates: /usr/bin/aptitude
    warn: false

- name: Install build prereqs
  apt:
    update_cache: true
    name:
      - build-essential
      - cmake
      - ninja-build
      - curl
  tags:
    - common
