---
- name: Install build prereqs
  ansible.builtin.apt:
    update_cache: true
    name:
      - build-essential
      - cmake
      - ninja-build
      - curl
      - gdb
      - cmake-curses-gui
      - pkg-config
      - libsystemd-dev
  tags:
    - common
