---
- name: Unarchive sources
  ansible.builtin.unarchive:
    src: https://github.com/catchorg/Catch2/archive/v{{ catch_version }}.tar.gz
    dest: /usr/local/src
    remote_src: true
  tags:
    - catch

- name: Create build directory
  ansible.builtin.file:
    path: /usr/local/src/Catch2-{{ catch_version }}/build
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - catch

- name: Run cmake
  ansible.builtin.command:
    chdir: /usr/local/src/Catch2-{{ catch_version }}/build
    argv:
      - /usr/bin/cmake
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr/local
      - -DCATCH_BUILD_TESTING=OFF
      - -DCATCH_INSTALL_DOCS=OFF
      - -GNinja
      - ..
  tags:
    - catch
    - build
    - cmake

- name: Build and install
  ansible.builtin.command:
    chdir: /usr/local/src/Catch2-{{ catch_version }}/build
    argv:
      - /usr/bin/ninja
      - install
  tags:
    - catch
    - build
