---
- name: Unarchive sources
  ansible.builtin.unarchive:
    src: https://github.com/LouisCharlesC/safe/archive/v{{ safe_version }}.tar.gz
    dest: /usr/local/src
    remote_src: true
  tags:
    - safe

- name: Create build directory
  ansible.builtin.file:
    path: /usr/local/src/safe-{{ safe_version }}/build
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - safe

- name: Run cmake
  ansible.builtin.command:
    chdir: /usr/local/src/safe-{{ safe_version }}/build
    argv:
      - /usr/bin/cmake
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr/local
      - -GNinja
      - ..
  tags:
    - safe
    - build
    - cmake

- name: Build and install
  ansible.builtin.command:
    chdir: /usr/local/src/safe-{{ safe_version }}/build
    argv:
      - /usr/bin/ninja
      - install
  tags:
    - safe
    - build
