/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
  // Apply the Kotlin JVM plugin to add support for Kotlin.
  id("org.jetbrains.kotlin.jvm") version "1.3.50"

  // Apply the application plugin to add support for building a CLI application.
  application
}

repositories {
  // Use jcenter for resolving dependencies.
  // You can declare any Maven/Ivy/file repository here.
  jcenter()
  maven(url = "http://first.wpi.edu/FRC/roborio/maven/release")
}

dependencies {
  val wpiVersion = "2019.4.1"
  implementation("org.strykeforce.thirdcoast:deadeye:19.4.1")
  implementation("ch.qos.logback:logback-classic:1.2.3")
  implementation("io.dropwizard.metrics:metrics-core:4.+")
  implementation("edu.wpi.first.ntcore:ntcore-java:$wpiVersion")
  implementation("edu.wpi.first.ntcore:ntcore-jni:$wpiVersion:all")
  implementation("edu.wpi.first.wpiutil:wpiutil-java:$wpiVersion")
  implementation("org.fusesource.jansi:jansi:1.18")
  implementation("com.github.ajalt:clikt:2.2.0")

  // Align versions of all Kotlin components
  implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

  // Use the Kotlin JDK 8 standard library.
  implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

  // Use the Kotlin test library.
  testImplementation("org.jetbrains.kotlin:kotlin-test")

  // Use the Kotlin JUnit integration.
  testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
}

application {
  // Define the main class for the application
  mainClassName = "org.strykeforce.deadeye.cli.AppKt"
}
