version: "3.4"

x-common-environment: &common-environment
  DEADEYE_NT_SERVER: 10.27.67.2
  DEADEYE_NT_PORT: 1735

x-common-restart: &common-restart
  restart: on-failure

volumes:
  upload_data:

services:
  daemon:
    image: j3ff/deadeye-daemon:4aa540b
    privileged: true
    ports:
      - 5805:5805
      - 5806:5806
      - 5807:5807
      - 5808:5808
      - 5809:5809
    volumes:
      - upload_data:/upload
    devices:
      - /dev/gpiochip0
      - "${CAMERA_DEV}:/dev/deadeye"
    environment:
      <<: *common-environment
      DEADEYE_STREAM_HOST: 10.27.67.219
    <<: *common-restart
  admin:
    image: j3ff/deadeye-admin:4aa540b
    ports:
      - 5000:5000
    volumes:
      - upload_data:/upload
    environment:
      <<: *common-environment
      PYTHONPATH: /app
      FLASK_ENV: production
      DEADEYE_ADMIN_PORT: 5000
      DEADEYE_NT_WAIT_MS: 500
      DEADEYE_UPLOAD_DIR: /upload
    stop_grace_period: 1s
    stop_signal: SIGINT
    <<: *common-restart
  web:
    image: j3ff/deadeye-web:4aa540b
    ports:
      - "0.0.0.0:80:80"
    <<: *common-restart