# just manual: https://github.com/casey/just#readme

default:
  @just --list

IMAGE := "j3ff/deadeye-daemon"
VERSION := `git rev-parse --short HEAD`

docker:
  nix build .#dockerImage
  ./result | docker load
  docker tag {{ IMAGE }}:latest {{ IMAGE }}:{{VERSION}}

run: docker
  docker run -it --rm --name deadeye-daemon --env-file .env {{IMAGE}}:{{VERSION}}


deploy: docker
  docker push {{ IMAGE }}:{{VERSION}}
