---
- name: Unarchive sources
  ansible.builtin.unarchive:
    src: https://github.com/wpilibsuite/allwpilib/archive/v{{ wpilib_version }}.tar.gz
    dest: /usr/local/src
    remote_src: true
  tags:
    - wpilib

- name: Create build directory
  ansible.builtin.file:
    path: /usr/local/src/allwpilib-{{ wpilib_version }}/build
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - wpilib

- name: Run cmake
  ansible.builtin.command:
    chdir: /usr/local/src/allwpilib-{{ wpilib_version }}/build
    argv:
      - /usr/bin/cmake
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr/local
      - -DWITH_JAVA=OFF
      - -DWITH_CSCORE=ON
      - -DWITH_WPIMATH=OFF
      - -DWITH_WPILIB=OFF
      - -DWITH_OLD_COMMANDS=OFF
      - -DWITH_EXAMPLES=OFF
      - -DWITH_TESTS=OFF
      - -DWITH_GUI=OFF
      - -DWITH_SIMULATION_MODULES=OFF
      - -DFLAT_INSTALL_WPILIB={{ "ON" if (ansible_architecture == "x86_64") else "OFF" }}
      - -GNinja
      - ..
  environment:
    LDFLAGS: -latomic
  tags:
    - wpilib
    - build
    - cmake

- name: Build and install
  ansible.builtin.command:
    chdir: /usr/local/src/allwpilib-{{ wpilib_version }}/build
    argv:
      - /usr/bin/ninja
      - install
  tags:
    - wpilib
    - build

- name: Copy ld config
  ansible.builtin.copy:
    content: /usr/local/wpilib/lib
    dest: /etc/ld.so.conf.d/wpilib.conf
    owner: root
    group: root
    mode: 0644
  register: wpilib_conf
  tags:
    - wpilib
    - build

- name: Update ld cache
  ansible.builtin.command: /sbin/ldconfig
  when: wpilib_conf is changed
  tags:
    - wpilib
    - build
