---
- name: Unarchive sources
  unarchive:
    src: https://github.com/wpilibsuite/allwpilib/archive/v{{ wpilib_version }}.tar.gz
    dest: /usr/local/src
    remote_src: true
  tags:
    - wpilib

- name: Create build directory
  file:
    path: /usr/local/src/allwpilib-{{ wpilib_version }}/build
    state: directory
  tags:
    - wpilib

- name: Run cmake
  command:
    chdir: /usr/local/src/allwpilib-{{ wpilib_version }}/build
    argv:
      - /usr/bin/cmake
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr/local
      - -DFLAT_INSTALL_WPILIB={{ "ON" if (ansible_distribution_release == "bionic" and ansible_architecture == "x86_64") else "OFF" }}
      - -DUSE_EXTERNAL_HAL=OFF
      - -DWITHOUT_ALLWPILIB=ON
      - -DWITHOUT_CSCORE=OFF
      - -DWITHOUT_JAVA=ON
      - -GNinja
      - ..
  environment:
    LDFLAGS: -latomic
  tags:
    - wpilib
    - build
    - cmake

- name: Build and install
  command:
    chdir: /usr/local/src/allwpilib-{{ wpilib_version }}/build
    argv:
      - /usr/bin/ninja
      - install
  tags:
    - wpilib
    - build

- name: Copy ld config
  copy:
    content: /usr/local/wpilib/lib
    dest: /etc/ld.so.conf.d/wpilib.conf
  register: wpilib_conf
  tags:
    - wpilib
    - build

- name: Update ld cache
  command: /sbin/ldconfig
  when: wpilib_conf is changed
  tags:
    - wpilib
    - build
