---
- name: Install node source
  ansible.builtin.shell:
    cmd: curl -sL https://deb.nodesource.com/setup_{{ deadeye_node_version }} | sudo -E bash -
    creates: /etc/apt/sources.list.d/nodesource.list
  args:
    warn: no

- name: Install node and npm
  ansible.builtin.apt:
    update_cache: yes
    state: present
    name:
      - nodejs
