[project]
authors = [{ name = "Jeff Hutchison", email = "jeff@jeffhutchison.com" }]
description = "Deadeye admin console back-end"
license = "MIT"
name = "deadeye"
version = "22.2.0"                                                        # updated by scripts/bump.py
requires-python = ">=3.11"

dependencies = [
"click==8.0.4",
  "eventlet==0.33.3",
  "flask==2.0.3",
  "flask-socketio==5.1.2",
  "pynetworktables==2021.0.0",
  "python-dotenv==0.18.0",
  "werkzeug==2.3.8",
  "dnspython==2.2.1",
]

[project.scripts]
deadeye = "deadeye.scripts.cli:main"
deadeye-server = "deadeye.scripts.server:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
