---
- name: Clone repo
  ansible.builtin.git:
    repo: https://github.com/intel/IntelSEAPI.git
    dest: /usr/local/src/IntelSEAPI
    version: "{{ seapi_version }}"
  register: seapi_clone
  tags:
    - seapi

- name: Build and install
  ansible.builtin.command: python buildall.py --install --force_bits=64 --no_java
  args:
    chdir: /usr/local/src/IntelSEAPI
  when: seapi_clone is changed
  tags:
    - seapi
