---
- name: Install build prereqs
  apt:
    update_cache: no
    name:
      - python3-virtualenv
      - python-virtualenv
      - python3-dev
      - python3-setuptools

- name: Install pip packages
  pip:
    requirements: "{{ deadeye_src }}/admin-server/requirements.txt"
    virtualenv: /opt/deadeye
    virtualenv_python: python3

- name: Clean admin dist dir
  file:
    path: "{{ deadeye_src }}/admin-server/dist"
    state: absent

- name: Link admin-web build files
  file:
    src: "{{ deadeye_src }}/admin-web/build"
    dest: "{{ deadeye_src }}/admin-server/deadeye/assets"
    state: link

- name: Build installation archive
  command:
    chdir: "{{ deadeye_src }}/admin-server"
    argv:
      - /usr/bin/python3
      - setup.py
      - sdist

- name: install sdist
  pip:
    virtualenv: /opt/deadeye
    virtualenv_python: python3
    name: file://{{ deadeye_src }}/admin-server/dist/deadeye-1.1.tar.gz
    state: latest
  tags: foo

-
