---
- name: Create admin requirements.txt
  ansible.builtin.command:
    chdir: "{{ playbook_dir }}/../admin"
    cmd: make requirements.txt
  delegate_to: localhost

- name: Create Deadeye wheel
  ansible.builtin.command:
    chdir: "{{ playbook_dir }}/../admin"
    cmd: make wheel
  delegate_to: localhost

- name: Install build prereqs
  ansible.builtin.apt:
    update_cache: false
    name:
      - virtualenv
      - python3-dev
      - python3-setuptools
      - libffi-dev

- name: Copy requirements.txt to Deadeye unit
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../admin/requirements.txt"
    dest: /opt/deadeye/requirements.txt
    mode: 0644

- name: Copy wheel to Deadeye unit
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../admin/dist/deadeye-{{ deadeye_version }}-py3-none-any.whl"
    dest: /opt/deadeye/deadeye-{{ deadeye_version }}-py3-none-any.whl
    mode: 0644

- name: Install pip packages
  ansible.builtin.pip:
    requirements: "/opt/deadeye/requirements.txt"
    virtualenv: /opt/deadeye
    virtualenv_python: python3

- name: Install wheel
  ansible.builtin.pip:
    virtualenv: /opt/deadeye
    virtualenv_python: python3
    name: file:///opt/deadeye/deadeye-{{ deadeye_version }}-py3-none-any.whl
    state: forcereinstall
  tags: foo

-
