---
- name: Install build prereqs
  apt:
    update_cache: no
    name:
      - cmake-curses-gui
      - pkg-config
      - libsystemd-dev

- name: Create build directory
  file:
    path: "{{ deadeye_src }}/build"
    state: directory
    mode: 0775

- name: Run cmake
  command:
    chdir: "{{ deadeye_src }}/build"
    argv:
      - /usr/bin/cmake
      - -GNinja
      - -DCMAKE_BUILD_TYPE={{ build_type }}
      - -DCMAKE_INSTALL_PREFIX=/opt/deadeye
      - -DCMAKE_CXX_FLAGS_RELEASE=-Ofast -march=native -mtune=native -flto -ffat-lto-objects -DNDEBUG
      - -DDEADEYE_BUILD_TESTS={{ deadeye_build_tests }}
      - -DDEADEYE_UNIT_ID={{ deadeye_unit }}
      - -DDEADEYE_CAMERA0_PIPELINE={{ camera_0_pipeline }}
      - -DDEADEYE_CAMERA1_PIPELINE={{ camera_1_pipeline }}
      - -DDEADEYE_CAMERA2_PIPELINE={{ camera_2_pipeline }}
      - -DDEADEYE_CAMERA3_PIPELINE={{ camera_3_pipeline }}
      - -DDEADEYE_CAMERA4_PIPELINE={{ camera_4_pipeline }}
      - ../daemon
  environment:
    LDFLAGS: -latomic
    CXXFLAGS: -Wno-psabi

- name: Build and Install
  command:
    chdir: "{{ deadeye_src }}/build"
    argv:
      - /usr/bin/ninja
      - install
