---
- name: Install prereqs
  apt:
    update_cache: true
    name:
      - git
      - cmake-curses-gui

- name: Set jhh authorized keys
  authorized_key:
    user: "{{ build_user }}"
    state: present
    key: https://github.com/jhh.keys

- name: Copy private deploy key
  copy:
    src: id_deadeye
    dest: "{{ deadeye_home }}/.ssh/"
    owner: "{{ build_user }}"
    group: "{{ build_user }}"
    mode: 0600

- name: Copy public deploy key
  copy:
    src: id_deadeye.pub
    dest: "{{ deadeye_home }}/.ssh/"
    owner: "{{ build_user }}"
    group: "{{ build_user }}"
    mode: 0664

- name: Configure ssh to use deploy key
  blockinfile:
    path: "{{ deadeye_home }}/.ssh/config"
    create: true
    owner: "{{ build_user }}"
    group: "{{ build_user }}"
    mode: 0600
    block: |
      Host lithium
        IdentityFile "{{ deadeye_home }}/.ssh/id_deadeye"

- name: Clone repo
  git:
    repo: "{{ deadeye_repo }}"
    dest: "{{ deadeye_home }}/deadeye"
    accept_hostkey: true
    key_file: "{{ deadeye_home }}/.ssh/id_deadeye"
  tags:
    - build

- name: Create build directory
  file:
    path: "{{ deadeye_home }}/deadeye/build"
    state: directory
  tags:
    - build
    - cmake

- name: Run cmake
  command:
    chdir: "{{ deadeye_home }}/deadeye/build"
    argv:
      - /usr/bin/cmake
      - -GNinja
      - -DCMAKE_BUILD_TYPE=Debug
      - -DCMAKE_INSTALL_PREFIX=/usr/local
      - -DDEADEYE_UNIT_ID={{ deadeye_unit }}
      - -DDEADEYE_CAMERA0_PIPELINE={{ camera_0_pipeline }}
      - -DDEADEYE_CAMERA1_PIPELINE={{ camera_1_pipeline }}
      - -DDEADEYE_CAMERA2_PIPELINE={{ camera_2_pipeline }}
      - -DDEADEYE_CAMERA3_PIPELINE={{ camera_3_pipeline }}
      - -DDEADEYE_CAMERA4_PIPELINE={{ camera_4_pipeline }}
      - ../daemon
  environment:
    LDFLAGS: -latomic
    CXXFLAGS: -Wno-psabi
  tags:
    - build
    - cmake

- name: Fix permissions
  file:
    path: "{{ deadeye_home }}/deadeye"
    owner: "{{ build_user }}"
    group: "{{ build_user }}"
    recurse: true
  tags:
    - build
    - cmake
