---
- name: Install prereqs
  apt:
    update_cache: true
    name:
      - git

- name: Set jhh authorized keys
  authorized_key:
    user: pi
    state: present
    key: https://github.com/jhh.keys

- name: Copy private deploy key
  copy:
    src: id_deadeye
    dest: "{{ deadeye_home }}/.ssh/"
    owner: pi
    group: pi
    mode: 0600

- name: Copy public deploy key
  copy:
    src: id_deadeye.pub
    dest: "{{ deadeye_home }}/.ssh/"
    owner: pi
    group: pi
    mode: 0664

- name: Configure ssh to use deploy key
  blockinfile:
    path: "{{ deadeye_home }}/.ssh/config"
    create: true
    owner: pi
    group: pi
    mode: 0600
    block: |
      Host lithium
        IdentityFile "{{ deadeye_home }}/.ssh/id_deadeye"

- name: Clone repo
  git:
    repo: "{{ deadeye_repo }}"
    dest: "{{ deadeye_home }}/deadeye"
    accept_hostkey: true
    key_file: "{{ deadeye_home }}/.ssh/id_deadeye"

- name: Create build directory
  file:
    path: "{{ deadeye_home }}/deadeye/build"
    state: directory

- name: Run cmake
  command:
    chdir: "{{ deadeye_home }}/deadeye/build"
    argv:
      - /usr/bin/cmake
      - -DCMAKE_BUILD_TYPE=Debug
      - -DCMAKE_INSTALL_PREFIX=/usr/local
      - -DDEADEYE_UNIT=C
      - -DDEADEYE_CAMERA0_PIPELINE=TestPatternPipeline
      - ..
  environment:
    LDFLAGS: -latomic
    CXXFLAGS: -Wno-psabi
  tags:
    - build
    - cmake

- name: Fix permissions
  file:
    path: "{{ deadeye_home }}/deadeye"
    owner: pi
    group: pi
    recurse: true
