---
- name: Install prereqs
  apt:
    update_cache: true
    name:
      - git
      - cmake-curses-gui
      - pkg-config
      - autoconf-archive
      - libsystemd-dev

- name: Set jhh authorized keys
  authorized_key:
    user: '{{ build_user }}'
    state: present
    key: https://github.com/jhh.keys

- name: Copy private deploy key
  copy:
    src: id_deadeye
    dest: '{{ deadeye_src }}/.ssh/'
    owner: '{{ build_user }}'
    group: '{{ build_user }}'
    mode: 0600

- name: Copy public deploy key
  copy:
    src: id_deadeye.pub
    dest: '{{ deadeye_src }}/.ssh/'
    owner: '{{ build_user }}'
    group: '{{ build_user }}'
    mode: 0664

- name: Configure ssh to use deploy key
  blockinfile:
    path: '{{ deadeye_src }}/.ssh/config'
    create: true
    owner: '{{ build_user }}'
    group: '{{ build_user }}'
    mode: 0600
    block: |
      Host github.com
        User git
        IdentityFile "{{ deadeye_src }}/.ssh/id_deadeye"
        IdentitiesOnly yes

- name: Clone repo
  git:
    repo: '{{ deadeye_repo }}'
    dest: '{{ deadeye_src }}/deadeye'
    accept_hostkey: true
    key_file: '{{ deadeye_src }}/.ssh/id_deadeye'
  tags:
    - build

- name: Create directories
  file:
    path: '{{ item }}'
    state: directory
    mode: 0775
  loop:
    - '{{ deadeye_src }}/deadeye/build'
    - '{{ deadeye_conf }}'
    - '{{ deadeye_mount }}'
  tags:
    - build
    - cmake
    - systemd

- name: Run cmake
  command:
    chdir: '{{ deadeye_src }}/deadeye/build'
    argv:
      - /usr/bin/cmake
      - -GNinja
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/opt/deadeye
      - -DCMAKE_CXX_FLAGS_RELEASE=-Ofast -march=native -mtune=native -flto -ffat-lto-objects -DNDEBUG
      - -DDEADEYE_UNIT_ID={{ deadeye_unit }}
      - -DDEADEYE_CAMERA0_PIPELINE={{ camera_0_pipeline }}
      - -DDEADEYE_CAMERA1_PIPELINE={{ camera_1_pipeline }}
      - -DDEADEYE_CAMERA2_PIPELINE={{ camera_2_pipeline }}
      - -DDEADEYE_CAMERA3_PIPELINE={{ camera_3_pipeline }}
      - -DDEADEYE_CAMERA4_PIPELINE={{ camera_4_pipeline }}
      - ../daemon
  environment:
    LDFLAGS: -latomic
    CXXFLAGS: -Wno-psabi
  tags:
    - build
    - cmake

- name: Build and Install
  command:
    chdir: '{{ deadeye_src }}/deadeye/build'
    argv:
      - /usr/bin/ninja
      - install
  tags:
    - build
    - cmake

- name: Copy optional config file
  copy:
    src: deadeye.conf
    dest: '{{ deadeye_conf }}'
    mode: 0664
    force: no
  tags:
    - systemd

- name: Copy systemd unit files
  copy:
    src: '{{ item }}'
    dest: /etc/systemd/system/
    mode: 0664
  loop:
    - deadeye-daemon.service
    - deadeye-shutdown.service
    - var-opt-deadeye.mount
  tags:
    - systemd

- name: Enable systemd services
  systemd:
    name: '{{ item }}'
    enabled: yes
    state: started
  loop:
    - deadeye-daemon.service
    - deadeye-shutdown.service
    - var-opt-deadeye.mount
  tags:
    - systemd
