---
- import_tasks: repo.yaml
  tags:
    - repo
    - deadeyed
    - admin

- import_tasks: deadeyed.yaml
  tags:
    - deadeyed

- import_tasks: systemd.yaml
  tags:
    - systemd

- import_tasks: admin-web.yaml
  tags:
    - admin

- import_tasks: admin-server.yaml
  tags:
    - admin
