---
- name: Set jhh authorized keys
  authorized_key:
    user: "{{ build_user }}"
    state: present
    key: https://github.com/jhh.keys

- name: Install git
  apt:
    update_cache: false
    name:
      - git

- name: Clone repo
  git:
    repo: "{{ deadeye_repo }}"
    dest: "{{ deadeye_src }}"
  register: deadeye_repo
