---
- name: create deadeye directory
  file:
    path: "{{ deadeye_dir }}"
    state: directory
    mode: 0755
    owner: root
    group: root

- name: sync remote repo from local
  ansible.posix.synchronize:
    src: ../../deadeye/daemon
    dest: "{{ deadeye_src }}"
    times: false
    checksum: true
    delete: true
    rsync_opts:
      - "--exclude *build*/"
  register: deadeye_repo