---
- name: Install nginx
  ansible.builtin.apt:
    update_cache: false
    name:
      - nginx

- name: Remove default Nginx config
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Install Nginx config
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/nginx.conf
    mode: 0640

- name: Remove previous build
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ playbook_dir }}/../web/build/"
    - "{{ playbook_dir }}/../web/node_modules/"
  delegate_to: localhost

- name: Install admin packages based on package.json
  ansible.builtin.command:
    chdir: "{{ playbook_dir }}/../web"
    argv:
      - npm
      - ci
  delegate_to: localhost

- name: Build admin front-end
  ansible.builtin.command:
    chdir: "{{ playbook_dir }}/../web"
    argv:
      - npm
      - run
      - build
  delegate_to: localhost

- name: Remove HTML dir
  ansible.builtin.file:
    path: "{{ nginx_html }}"
    state: absent

- name: Create HTML dir
  ansible.builtin.file:
    path: "{{ nginx_html }}"
    state: directory
    mode: 0775

- name: Copy admin front-end to HTML dir
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../web/build/"
    dest: "{{ nginx_html }}"
    mode: preserve
