---
- name: Unarchive sources
  ansible.builtin.unarchive:
    src: https://github.com/jhh/tinyfsm/archive/v{{ tinyfsm_version }}.tar.gz
    dest: /usr/local/src
    remote_src: true
  tags:
    - tinyfsm

- name: Create build directory
  ansible.builtin.file:
    path: /usr/local/src/tinyfsm-{{ tinyfsm_version }}/build
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - tinyfsm

- name: Run cmake
  ansible.builtin.command:
    chdir: /usr/local/src/tinyfsm-{{ tinyfsm_version }}/build
    argv:
      - /usr/bin/cmake
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr/local
      - -GNinja
      - ..
  tags:
    - tinyfsm
    - build
    - cmake

- name: Build and install
  ansible.builtin.command:
    chdir: /usr/local/src/tinyfsm-{{ tinyfsm_version }}/build
    argv:
      - /usr/bin/ninja
      - install
  tags:
    - tinyfsm
    - build
