---
- hosts: deadeye
  roles:
    - role: wpilib
      tags: wpilib
    - role: spdlog
      tags: spdlog
    - role: nlohmann_json
      tags: [json, nlohmann_json]
    - role: catch
      tags: catch
    - role: deadeye
      tags: deadeye
