---
deadeye:
  hosts:
    deadeye-b:
      ansible_host: deadeye-b.local
      ansible_user: jeff
      build_user: jeff
      build_type: Debug
      deadeye_unit: B
      camera_0_pipeline: TestPatternPipeline
      camera_1_pipeline: TestPatternPipeline
    deadeye-c:
      ansible_host: pi
      ansible_user: pi
      build_user: jeff
      build_type: Debug
      deadeye_unit: C
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_become: true
    camera_0_pipeline: TestPatternPipeline
    camera_1_pipeline:
    camera_2_pipeline:
    camera_3_pipeline:
    camera_4_pipeline:

bootstrap:
  hosts:
    raspberrypi:
      ansible_host: raspberrypi.local
      ansible_user: pi
      ansible_become: true
      ansible_python_interpreter: /usr/bin/python3
