---
deadeye:
  hosts:
    deadeye-a:
      ansible_host: deadeye-a.local
      ansible_user: deadeye
      deadeye_unit: A
      camera_0_pipeline: deadeye::MinAreaRectPipeline
    deadeye-b:
      ansible_host: deadeye-b.local
      ansible_user: jeff
      deadeye_unit: B
      camera_0_pipeline: deadeye::DefaultPipeline
      camera_1_pipeline: deadeye::DefaultPipeline
    deadeye-c:
      ansible_host: deadeye-c.local
      ansible_user: deadeye
      deadeye_unit: C
      camera_0_pipeline: deadeye::MinAreaRectPipeline
      camera_1_pipeline: deadeye::UprightRectPipeline
    deadeye-d:
      ansible_host: deadeye-d.local
      ansible_user: deadeye
      deadeye_unit: D
      camera_0_pipeline: deadeye::MinAreaRectPipeline
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_become: true
    build_user: root
    build_type: Release
    camera_0_pipeline:
    camera_1_pipeline:
    camera_2_pipeline:
    camera_3_pipeline:
    camera_4_pipeline:
    install_opencv: false

bootstrap:
  hosts:
    raspberrypi:
      ansible_host: deadeye-d.local
      ansible_user: jeff
      ansible_become: true
      ansible_python_interpreter: /usr/bin/python3
