---
deadeye:
  hosts:
    deadeye-a:
      ansible_host: deadeye-a
      deadeye_unit: A
      camera_0_pipeline: deadeye::MinAreaRectPipeline
    deadeye-b:
      ansible_host: deadeye-b
      deadeye_unit: B
      camera_0_pipeline: deadeye::DefaultPipeline
      camera_1_pipeline: deadeye::DefaultPipeline
    deadeye-c:
      ansible_host: deadeye-c
      deadeye_unit: C
      camera_0_pipeline: deadeye::MinAreaRectPipeline
      camera_1_pipeline: deadeye::UprightRectPipeline
    deadeye-d:
      ansible_host: deadeye-d
      deadeye_unit: D
      camera_0_pipeline: deadeye::MinAreaRectPipeline
    deadeye-h:
      ansible_host: deadeye-h.local
      deadeye_unit: H
      camera_0_pipeline: deadeye::UprightRectPipeline
      camera_1_pipeline: deadeye::MinAreaRectPipeline
      install_opencv: true
    deadeye-t:
      ansible_host: deadeye-t.local
      deadeye_unit: T
      camera_0_pipeline: deadeye::MinAreaRectPipeline
      install_opencv: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: deadeye
    ansible_become: true
    build_user: root
    build_type: Release
    camera_0_pipeline:
    camera_1_pipeline:
    camera_2_pipeline:
    camera_3_pipeline:
    camera_4_pipeline:
    install_opencv: false

bootstrap:
  hosts:
    raspberrypi:
      ansible_host: deadeye-d.local
      ansible_user: jeff
      ansible_become: true
      ansible_python_interpreter: /usr/bin/python3
