---
deadeye:
  hosts:
    deadeye-a:
      ansible_host: deadeye-a
      deadeye_unit: A
      camera_0_pipeline: deadeye::MinAreaRectPipeline
    deadeye-b:
      ansible_host: deadeye-b
      deadeye_unit: B
      camera_0_pipeline: deadeye::UprightRectPipeline
    deadeye-c:
      ansible_host: deadeye-c
      deadeye_unit: C
      camera_0_pipeline: deadeye::TargetListPipeline
      camera_1_pipeline: deadeye::UprightRectPipeline
      camera_2_pipeline: deadeye::MinAreaRectPipeline
    deadeye-d:
      ansible_host: deadeye-d
      deadeye_unit: D
      camera_0_pipeline: deadeye::MinAreaRectPipeline
    deadeye-f:
      ansible_host: deadeye-f.local
      deadeye_unit: F
      camera_0_pipeline: deadeye::UprightRectPipeline
      install_opencv: true
      ansible_user: deadeye
    deadeye-h:
      ansible_host: deadeye-h
      deadeye_unit: H
      camera_0_pipeline: deadeye::UprightRectPipeline
      camera_1_pipeline: deadeye::MinAreaRectPipeline
      camera_2_pipeline: deadeye::TargetListPipeline
      install_opencv: true
    deadeye-i:
      ansible_host: deadeye-i
      deadeye_unit: I
      camera_0_pipeline: deadeye::UprightRectPipeline
      camera_1_pipeline: deadeye::MinAreaRectPipeline
      camera_2_pipeline: deadeye::TargetListPipeline
      install_opencv: true
    deadeye-j:
      ansible_host: deadeye-j
      deadeye_unit: J
      camera_0_pipeline: deadeye::UprightRectPipeline
      camera_1_pipeline: deadeye::MinAreaRectPipeline
      camera_2_pipeline: deadeye::TargetListPipeline
      install_opencv: true
    deadeye-k:
      ansible_host: deadeye-k
      deadeye_unit: K
      camera_0_pipeline: deadeye::UprightRectPipeline
      camera_1_pipeline: deadeye::MinAreaRectPipeline
      camera_2_pipeline: deadeye::TargetListPipeline
      install_opencv: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: deadeye
    ansible_become: true
    build_user: root
    build_type: Release
    camera_0_pipeline:
    camera_1_pipeline:
    camera_2_pipeline:
    camera_3_pipeline:
    camera_4_pipeline:
    install_opencv: false

bootstrap:
  hosts:
    raspberrypi:
      ansible_host: deadeye-d.local
      ansible_user: jeff
      ansible_become: true
      ansible_python_interpreter: /usr/bin/python3
