---
- name: Unarchive sources
  unarchive:
    src: https://github.com/jhh/readerwriterqueue/archive/v{{ readerwriterqueue_version }}.tar.gz
    dest: /usr/local/src
    remote_src: true
  tags:
    - readerwriterqueue

- name: Create build directory
  file:
    path: /usr/local/src/readerwriterqueue-{{ readerwriterqueue_version }}/build
    state: directory
  tags:
    - readerwriterqueue

- name: Run cmake
  command:
    chdir: /usr/local/src/readerwriterqueue-{{ readerwriterqueue_version }}/build
    argv:
      - /usr/bin/cmake
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr/local
      - -GNinja
      - ..
  tags:
    - readerwriterqueue
    - build
    - cmake

- name: Build and install
  command:
    chdir: /usr/local/src/readerwriterqueue-{{ readerwriterqueue_version }}/build
    argv:
      - /usr/bin/ninja
      - install
  tags:
    - readerwriterqueue
    - build
