---
- name: Unarchive sources
  ansible.builtin.unarchive:
    src: https://github.com/cameron314/readerwriterqueue/archive/v{{ readerwriterqueue_version }}.tar.gz
    dest: /usr/local/src
    remote_src: true
  tags:
    - readerwriterqueue

- name: Create build directory
  ansible.builtin.file:
    path: /usr/local/src/readerwriterqueue-{{ readerwriterqueue_version }}/build
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - readerwriterqueue

- name: Run cmake
  ansible.builtin.command:
    chdir: /usr/local/src/readerwriterqueue-{{ readerwriterqueue_version }}/build
    argv:
      - /usr/bin/cmake
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr/local
      - -GNinja
      - ..
  tags:
    - readerwriterqueue
    - build
    - cmake

- name: Build and install
  ansible.builtin.command:
    chdir: /usr/local/src/readerwriterqueue-{{ readerwriterqueue_version }}/build
    argv:
      - /usr/bin/ninja
      - install
  tags:
    - readerwriterqueue
    - build
