---
- name: Install build prereqs
  ansible.builtin.apt:
    update_cache: false
    name:
      - autoconf-archive

- name: Unarchive sources
  ansible.builtin.unarchive:
    src: "{{ libgpiod_repo }}/snapshot/{{ libgpiod_dir }}.tar.gz"
    dest: /usr/local/src
    remote_src: true
  tags:
    - libgpiod

- name: Run autogen
  ansible.builtin.command:
    chdir: /usr/local/src/{{ libgpiod_dir }}
    creates: /usr/local/src/{{ libgpiod_dir }}/config.status
    argv:
      - /usr/local/src/{{ libgpiod_dir }}/autogen.sh
      - --enable-tools=yes
      - --prefix=/usr/local
  register: libgpiod_autogen
  tags:
    - libgpiod
    - build
    - autogen

- name: Build and Install C library
  ansible.builtin.command:
    chdir: /usr/local/src/{{ libgpiod_dir }}
    argv:
      - /usr/bin/make
      - install
  when: libgpiod_autogen is changed
  tags:
    - libgpiod
    - build

- name: Build and Install C++ library
  ansible.builtin.command:
    chdir: /usr/local/src/{{ libgpiod_dir }}/bindings/cxx
    argv:
      - /usr/bin/make
      - install
  when: libgpiod_autogen is changed
  tags:
    - libgpiod
    - build

- name: Register libraries
  ansible.builtin.command:
    argv:
      - /sbin/ldconfig
  when: libgpiod_autogen is changed
  tags:
    - libgpiod
    - build
