---
- name: Install build prereqs
  ansible.builtin.apt:
    update_cache: false
    name:
      - autoconf-archive

- name: Unarchive sources
  ansible.builtin.unarchive:
    src: https://git.kernel.org/pub/scm/libs/libgpiod/libgpiod.git\
      /snapshot/libgpiod-{{ libgpiod_version }}.tar.gz
    dest: /usr/local/src
    remote_src: true
  tags:
    - libgpiod

- name: Run autogen
  ansible.builtin.command:
    chdir: /usr/local/src/libgpiod-{{ libgpiod_version }}
    creates: /usr/local/src/libgpiod-{{ libgpiod_version }}/config.status
    argv:
      - /usr/local/src/libgpiod-{{ libgpiod_version }}/autogen.sh
      - --enable-tools=yes
      - --prefix=/usr/local
  register: libgpiod_autogen
  tags:
    - libgpiod
    - build
    - autogen

- name: Build and Install C library
  ansible.builtin.command:
    chdir: /usr/local/src/libgpiod-{{ libgpiod_version }}
    argv:
      - /usr/bin/make
      - install
  when: libgpiod_autogen is changed
  tags:
    - libgpiod
    - build

- name: Build and Install C++ library
  ansible.builtin.command:
    chdir: /usr/local/src/libgpiod-{{ libgpiod_version }}/bindings/cxx
    argv:
      - /usr/bin/make
      - install
  when: libgpiod_autogen is changed
  tags:
    - libgpiod
    - build

- name: Register libraries
  ansible.builtin.command:
    argv:
      - /sbin/ldconfig
  when: libgpiod_autogen is changed
  tags:
    - libgpiod
    - build
