[book]
authors = ["Jeff Hutchison"]
language = "en"
multilingual = false
src = "src"
title = "Deadeye Vision System"

[output.html]
additional-css = ["custom.css"]
site-url = "https://strykeforce.github.io/deadeye"
git-repository-url = "https://github.com/strykeforce/deadeye"
