---
- name: Unarchive sources
  ansible.builtin.unarchive:
    src: https://github.com/fmtlib/fmt/archive/{{ fmt_version }}.tar.gz
    dest: /usr/local/src
    remote_src: true
  tags:
    - fmt

- name: Create build directory
  ansible.builtin.file:
    path: /usr/local/src/fmt-{{ fmt_version }}/build
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - fmt

- name: Run cmake
  ansible.builtin.command:
    chdir: /usr/local/src/fmt-{{ fmt_version }}/build
    argv:
      - /usr/bin/cmake
      - -DCMAKE_BUILD_TYPE=Release
      - -DBUILD_SHARED_LIBS=TRUE
      - -DCMAKE_INSTALL_PREFIX=/usr/local
      - -DFMT_DOC=OFF
      - -DFMT_TEST=OFF
      - -GNinja
      - ..
  tags:
    - fmt
    - build
    - cmake

- name: Build and install
  ansible.builtin.command:
    chdir: /usr/local/src/fmt-{{ fmt_version }}/build
    argv:
      - /usr/bin/ninja
      - install
  tags:
    - fmt
    - build
